services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_crm_spring_boot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10
    networks:
      - gym-net

  mongo:
    image: mongo:8
    container_name: gym_workload_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - gym-net

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - gym-net

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - gym-net

  trainer-workload:
    build: ../trainer-workload
    image: trainer-workload:1.0
    container_name: trainer-workload
    depends_on:
      - mongo
      - activemq
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_MONGODB_HOST: mongo
      MQ_ADMIN_USERNAME: ${MQ_ADMIN_USERNAME}
      MQ_ADMIN_PASSWORD: ${MQ_ADMIN_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - gym-net

  crm:
    build: .
    image: gym-crm:1.0
    container_name: gym-crm
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_started
      trainer-workload:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: local
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      WORKLOAD_SERVICE_URL: http://trainer-workload:8081
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MQ_ADMIN_USERNAME: ${MQ_ADMIN_USERNAME}
      MQ_ADMIN_PASSWORD: ${MQ_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_ADMIN_USERNAME: ${APP_ADMIN_USERNAME}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
    networks:
      - gym-net

volumes:
  postgres_data:
  mongo_data:

networks:
  gym-net:
    driver: bridge