spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.gym.crmspringboot: WARN